apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: demoproject
spec:
  params:
    - default: 'python:3'
      name: BASE_IMAGE
      type: string
    - default: 'https://github.com/pandeybk/rhoai-custom-image-pipeline.git'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default:
        - RUN pip install faker
        - RUN pip install calc
      name: DOCKER_STEPS
      type: array
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: helm-upgrade-from-source
      params:
        - name: charts_dir
          value: rhoai-image-custom-package
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: helm-upgrade-from-source
        - name: release_namespace
          value: redhat-ods-applications
        - name: overwrite_values
          value: >-
            base_image=$(params.BASE_IMAGE)
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
        - name: upgrade_extra_params
          value: '--debug '
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: workspace
    - name: openshift-client
      params:
        - name: SCRIPT
          value: >-
            oc start-build helm-upgrade-from-source  -n redhat-ods-applications
            --follow
        - name: VERSION
          value: '4.13'
      runAfter:
        - helm-upgrade-from-source
      taskRef:
        kind: Task
        name: openshift-client
  workspaces:
    - name: workspace
  resources: []
  finally: []
