apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Release.Name }}
  namespace: redhat-ods-applications
spec:
  source:
    type: Dockerfile
    dockerfile: |-
      FROM demo
      {{- range .Values.dockerSteps }}
      {{ . | indent 4 }}
      {{- end }}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: '{{ .Values.base_image }}'
  output:
    to:
      kind: ImageStreamTag
      namespace: redhat-ods-applications
      name: '{{ .Release.Name }}:{{ .Release.Name }}'
